---
name: MojoX-Renderer-XSLT
version: 0.01
author:
  - 'Bob Faist <bfaist@cpan.org>'
abstract: The great new MojoX::Renderer::XSLT!
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  FindBin: 1.49
  Mojo: 0.999923
  Test::More: 0.92
  XML::LibXML: 1.69
  XML::LibXSLT: 1.68
provides:
  MojoX::Renderer::XSLT:
    file: lib/MojoX/Renderer/XSLT.pm
    version: 0.01
  MojoX::Renderer::XSLT::XML::LibXSLT:
    file: lib/MojoX/Renderer/XSLT/XML/LibXSLT.pm
    version: 0.01
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
